### ISSUE TITLE
Phương thức createUserProject

### ISSUE THREAD

**Issue by HaN4K0** [NPNKhoa/CT240-backend#16]
Lỗi không thể tạo user project
![createUserProject](https://github.com/user-attachments/assets/886627fb-e068-41f6-b0a3-000d334219a3)

**Comment by NPNKhoa** [comment]
Xem kỹ lại, cái này là tạo project mà. Với lại nó cũng đc chứ đâu có lỗi đâu ta
![image](https://github.com/user-attachments/assets/ba2d6d62-f777-4f7b-b4a3-c6737dde6e3b)
