### ISSUE TITLE
Phương thức createProject

### ISSUE THREAD

**Issue by HaN4K0** [NPNKhoa/CT240-backend#19]
- projectType yêu cầu phải là kiểu string (ảnh 1)
![createProject_1](https://github.com/user-attachments/assets/55949cba-02a9-45bf-83ae-3aa3bcd1b6ac)

- Khi đổi projectType qua kiểu string thì lại dính lỗi này O_O (ảnh 2). Nguyên văn lỗi là:
{
    "message": "Internal server error",
    "error": "Project validation failed: projectType: Cast to ObjectId failed for value \"123124dasd\" (type string) at path \"projectType\" because of \"BSONError\""
}
![createProject](https://github.com/user-attachments/assets/4b1049c1-c509-4504-b764-d89e0181eebc)

**Comment by NPNKhoa** [comment]
Cái projectType cho nó là cái giá trị của _id (6717afb...8844).
Tất cả những trường nào mà liên kết với document khác (bảng khác á), có thể hiểu là khóa ngoại, thì phải đưa id cho nó là cái giá trị của _id
@HaN4K0
