### ISSUE TITLE
Phương thức createUserProject

### ISSUE THREAD

**Issue by HaN4K0** [NPNKhoa/CT240-backend#21]
- Trường projectId để kiểu string thì bị báo lỗi như hình dưới :v
![image](https://github.com/user-attachments/assets/c06dd6f6-7563-4ff1-a5d7-4be9e6b683cd)

- Còn để thế này thì lại bị báo là:
{
    "message": "\"projectId\" must be a string"
}
![image](https://github.com/user-attachments/assets/091647ec-6304-48f7-b59b-18178c7f6378)

**Comment by NPNKhoa** [comment]
giống như cái kia, vẫn là khóa ngoại nên phải tryền giá trị của thằng _id @HaN4K0
