### ISSUE TITLE
Phương thức createSample

### ISSUE THREAD

**Issue by HaN4K0** [NPNKhoa/CT240-backend#22]
- phaseId yêu cầu kiểu string
![image](https://github.com/user-attachments/assets/92bd5d4e-64a6-495c-9865-99181c6bea0a)

- Đổi qua kiểu string thì bị báo là:
![image](https://github.com/user-attachments/assets/6b45eb5b-08aa-4c19-ab32-b147bf11bb61)

**Comment by NPNKhoa** [comment]
...
