### ISSUE TITLE
Phương thức createResponse

### ISSUE THREAD

**Issue by HaN4K0** [NPNKhoa/CT240-backend#23]
Lỗi không thể tạo responses
![image](https://github.com/user-attachments/assets/93a589bd-6513-4840-a81d-346d7f4e4be9)

**Comment by NPNKhoa** [comment]
Fix xong lỗi Internal Server Error. Tuy nhiên tạm thời chưa test api này tiếp do chưa hoàn thiện
@HaN4K0
