### ISSUE TITLE
Phương thức uploadFile

### ISSUE THREAD

**Issue by HaN4K0** [NPNKhoa/CT240-backend#24]
Lỗi không thể upload file
![image](https://github.com/user-attachments/assets/6785822f-a5a8-42de-ac06-b0f1e29acd75)

**Comment by NPNKhoa** [comment]
@HaN4K0 
CÁCH ĐỂ TEST CÁC API CÓ FILE:
- Chọn form-data cho body:
![image](https://github.com/user-attachments/assets/0894ab11-f213-470c-b692-29f6521929fe)
- Đổi type lại thành file:
![image](https://github.com/user-attachments/assets/43805668-16f1-498c-8dfe-01f994b56add)
- Để tên trường đúng với tên trên server:
![image](https://github.com/user-attachments/assets/8d6fd617-0f83-446f-90ba-d97d6d302595)
![image](https://github.com/user-attachments/assets/68d0c22f-8e7f-48d3-bee9-367efe130eba)
- Upload file từ máy tính:
![image](https://github.com/user-attachments/assets/fb2ca2e8-9158-4889-b771-c826e9beaaec)

Kết quả:
![image](https://github.com/user-attachments/assets/c3c5fa87-d0a2-4c16-b9ed-3dfa59364291)


**Test với các loại files khác (pdf, doc, txt,...)**
