### ISSUE TITLE
Phương thức createPhase

### ISSUE THREAD

**Issue by HaN4K0** [NPNKhoa/CT240-backend#25]
- Khi thiếu cả 2 trường startDate và endDate hoặc thiếu 1 trong 2 trường đều bị lỗi 500 như hình bên dưới và bị app crashed trong VS Code luôn
![image](https://github.com/user-attachments/assets/ecf3026e-1e5d-4827-85df-0618803d4109)

**Comment by NPNKhoa** [comment]
@khanh141 validate đi bạn
