### ISSUE TITLE
Phương thức createPhase

### ISSUE THREAD

**Issue by HaN4K0** [NPNKhoa/CT240-backend#26]
Có thể tạo được phase có ngày kết thúc trước cả ngày bắt đầu :v
![image](https://github.com/user-attachments/assets/47fefed6-d9a5-4f8b-9d0d-95e967bb6e8b)

**Comment by NPNKhoa** [comment]
@khanh141 validate tiếp bạn ơi. CÓ thể tham khảo code của t
