### ISSUE TITLE
GetUserProject

### ISSUE THREAD

**Issue by MPhus** [NPNKhoa/CT240-backend#30]
GetUserProject: khi lấy project mình đã tham gia (mình không phải chủ sở hữu) nhưng có trả về những project mình đã tạo.

**Comment by MPhus** [comment]
![image](https://github.com/user-attachments/assets/3ea1b67d-0fa2-4224-9e9a-5cdf05bea45a)

**Comment by NPNKhoa** [comment]
Dùng endpoint /join

Cập nhật lại cái own project thành endpoint /own

@HaN4K0 Test 2 endpoint này gấp
